<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>docs.output</string>
        <key>fileTypes</key>
        <array>
            <string>log</string>
        </array>
        <key>name</key>
        <string>Log file</string>
        <key>patterns</key>
        <array>
            <dict>
                <!-- Quoted strings with " -->
                <key>match</key>
                <string>"(.*?)"</string>
                <key>name</key>
                <string>string.quoted</string>
            </dict>
            <dict>
                <!-- Quoted strings with ' -->
                <key>match</key>
                <string>'(.*?)'</string>
                <key>name</key>
                <string>string.quoted</string>
            </dict>
            <dict>
                <!-- email address -->
                <key>match</key>
                <string>\S+@\S+\.\S+</string>
                <key>name</key>
                <string>markup.bold</string>
            </dict>
            <dict>
                <!-- Time -->
                <key>match</key>
                <string>\b[0-9]*(\:[0-9]*)+\b</string>
                <key>name</key>
                <string>constant.numeric</string>
            </dict>
            <dict>
                <!-- Numeric (decimal) -->
                <key>match</key>
                <string>\b\d+\.?\d*?\b</string>
                <key>name</key>
                <string>constant.numeric</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(Exception|Error|Failure|Fail|Fatal|false))(\:|\b)</string>
                <key>name</key>
                <string>invalid.illegal</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(warning|warn))(\:|\b)</string>
                <key>name</key>
                <string>string.quoted</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(hint|info|suggestion))(\:|\b)</string>
                <key>name</key>
                <string>keyword</string>
            </dict>
            <dict>
                <!-- log code -->
                <key>match</key>
                <string>^(?i:\w*(-\w*)+)(\:|\b)</string>
                <key>name</key>
                <string>entity.other.attribute-name</string>
            </dict>
            <dict>
                <!-- Tag -->
                <key>match</key>
                <string>^(?i:\[[\w\.]*\])</string>
                <key>name</key>
                <string>keyword</string>
            </dict>
            <dict>
                <!-- Generic URI/URL -->
                <key>match</key>
                <string>\b(?i:([a-z]|[0-9])+\:((\/\/)|((\/\/)?(\S)))+)</string>
                <key>name</key>
                <string>storage</string>
            </dict>
        </array>
    </dict>
</plist>